Vagrant.configure("2") do |config|
  config.vm.box = "gce"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.pty = true

  config.vm.provider :google do |google, override|
    google.name      = "bigtop"
    google.zone      = "asia-east1-a" # Changhua County, Taiwan
    google.image     = "centos-6-v20150423"
    google.disk_size = 40
    google.disk_name = "bigtop"
    override.ssh.username = ENV['USER']
    override.ssh.private_key_path = ENV['GOOGLE_SSH_KEY_LOCATION']
    override.vm.provision :shell do |shell|
      shell.path = "provision.sh"
    end
  end

end
