Vagrant.configure("2") do |config|
  config.vm.box = "gce"

  ## Issue:
  ## Reference:
  # [1] https://github.com/mitchellh/vagrant/issues/1482
  # [2] https://www.shell-tips.com/2014/09/08/sudo-sorry-you-must-have-a-tty-to-run-sudo/
  # config.ssh.pty = true

  config.vm.provider :google do |google, override|
    google.name      = "bigtop2"
    google.zone      = "asia-east1-a" # Changhua County, Taiwan
    google.image     = "ubuntu-1404-trusty-v20150316"
    google.disk_size = 40
    google.disk_name = "bigtop2"
    override.ssh.username = ENV['USER']
    override.ssh.private_key_path = ENV['GOOGLE_SSH_KEY_LOCATION']
    override.vm.provision :shell do |shell|
      shell.path = "provision.sh"
    end
  end

end
