Vagrant.configure("2") do |config|
  config.vm.box = "gce"

  ## Issue:
  ## Reference:
  # [1] https://github.com/mitchellh/vagrant/issues/1482
  # [2] https://www.shell-tips.com/2014/09/08/sudo-sorry-you-must-have-a-tty-to-run-sudo/
  config.ssh.pty = true

  config.vm.provider :google do |google, override|
    google.name      = "bigtop1"
    google.zone      = "asia-east1-a" # Changhua County, Taiwan
    google.image     = "centos-6-v20150423"
    google.disk_size = 40
    google.disk_name = "bigtop1"
    override.ssh.username = ENV['USER']
    override.ssh.private_key_path = ENV['GOOGLE_SSH_KEY_LOCATION']
    ## Note: comment follow steps to demo steps without provision scripts
    #override.vm.provision :shell do |shell|
    #  shell.path = "provision.sh"
    #end
  end

end
